/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imageHandling */

#ifndef _Included_imageHandling
#define _Included_imageHandling
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
